apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-medicure
  template:
    metadata:
      labels:
        app: healthcare-medicure
    spec:
      containers:
        - name: healthcare-medicure
          image: geethadinesh/healthcare-pipeline:v1.1
          ports:
            - containerPort: 80

