apiVersion: v1
kind: Service
metadata:
  name: healthcare-medicure-service
spec:
  type: LoadBalancer
  selector:
    app: healthcare-medicure
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
