name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t pawpal-help-center-image .
          docker images  # Optional: List Docker images for verification

      - name: Tag Docker image
        run: docker tag pawpal-help-center-image ${{ secrets.DOCKER_USERNAME }}/pawpal-help-center:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pawpal-help-center:latest
